#!/usr/bin/env -S bash -e

#
# The MIT License (MIT)
# Copyright (c) 2021 Li-Pro.Net (Stephan Linz)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
# OR OTHER DEALINGS IN THE SOFTWARE.
#

DRAWIO_OPT="--export --format pdf --crop --transparent --border 10 --page-index 1"
DRAWIO_BIN="$(type -P drawio)" || ( \
              echo "Executable not found: 'drawio'" >&2 ; exit 1 )

PDFTOCAIRO_OPT="-svg -nocrop -noshrink -nocenter -f 1 -l 1"
PDFTOCAIRO_BIN="$(type -P pdftocairo)" || ( \
                  echo "Executable not found: 'pdftocairo'" >&2 ; exit 1 )

for drawio in *.drawio; do
  pdf="${drawio%.drawio}.pdf"
  svg="${drawio%.drawio}.svg"
  ${DRAWIO_BIN} ${DRAWIO_OPT} --output "${pdf}" "${drawio}"
  ${PDFTOCAIRO_BIN} ${PDFTOCAIRO_OPT} "${pdf}" "${svg}"
  echo "${pdf} -> ${svg}"
  rm -vf "${pdf}"
done

exit 0

# ############################################################################
# vim: ft=bash ts=2 sw=2 et:
